### PR TITLE
Add code to remove django warning

### PR DESCRIPTION
**Pull request by hotline-emu**
### Why is this change proposed?

I've got a recurring error on my server that is easily removed solely by adding this to the config file. It should be the default that the code already falls through to. The only difference is that by adding this to the config, the warning will no longer show up.

### CODE REVIEW

**Comment by jerch** [comment]
@hotline-emu Can you give a more detailed info about the warnings you are getting? Any why you are gettings those? Normally the `computedfields` app should not create models on its own, thus should not need this setting in its app config.
Furthermore, your hardcoded value to `AutoField` is only the fallback for older django version, imho it defaults to `BigAutoField` in newer versions.

**Comment by hotline-emu** [comment]
@jerch - Thanks for correcting me on the AutoField misstatement, I'd rather know I was wrong than continue to be wrong. I'm in the process of converting a legacy app from Django 2.0 to 3.2 before going on to 4.0. This was one of the warning notices that has been popping up on my terminal every new run as I attempt to get the application on it's feet again.

Some of the legacy codebase is notably janky, I wasn't around when it was written. I wouldn't be surprised to learn that nobody else who uses this library doesn't see this warning in their terminal. FWIW, the warning does point back to the file being located in site-packages. I do find it odd that system check would be linting files in site-packages in the first place to this degree (especially with respect to warnings).

Regardless, it was a quick fix to drop the warning. I'm entirely unbothered if you don't feel this merge is necessary.

**Comment by jerch** [comment]
Ah no worries, was just trying to understand why you get thw warnings in the first place.

Since you upgrade from a much older pre 2.2 django version - I am not sure, if thats possible with computedfields simply by pulling newer versions. There were indeed some crucial changes that might break without further manual assistance:
- older versions used to have its own metaclass for `ComputedFieldsModel` (thats prolly the reason for your warning), while version >=0.1.0 uses a mixin concept for easier class inheritance
- `depends` syntax slightly changed from 0.1.0 onwards

To be one the safe side, I'd suggest the following steps ():
- create fixtures for all defined computed fields with old versions (to be used as backups)
- upgrade django + computedfields and other packages
- apply new `depends` syntax to all defined computed fields (watch out for fields from the same model, now to be placed under a _self_ rule)
- run `./manage.py updatedata`
- safety measure: compare freshly created cf values with values from the fixtures, if all matches you re good to go, if they differ, then you prolly have something missed with the new depends syntax (then repeat last steps until things match)

**Comment by hotline-emu** [comment]
Thanks, I'm gonna close this one out. You were spot on in identifying some stale code that was missing, specifically the depends syntax. I do still see the warning, but I suspect it has a lot more to do with the specific architecture of this monolithic repository than it does with the actual usage of computed fields.

**Pull request closed without merging**
