### PR TITLE
Add Django 5.0 And Python 3.12 Compatibility 

### PR DESCRIPTION
**Pull request by ckarli**
Removed Python 3.7 as it's deprecated

### CODE REVIEW

**Comment by jerch** [comment]
@ckarli Does not work yet with django 5. The tests fail at `Model.objects.create` ending up at:
```
ValueError: Model instances passed to related filters must be saved.
```
Had no time yet to look into django 5 changes. On a sidenote - I remember seeing something similar for backrelations startting to require a pk around 4.1 or 4.2, which was not the case before.

**Comment by jerch** [comment]
Btw you can also remove the django 3.2 tests, I am not keen to cover more than one LTS version in the long run.

**Comment by martinlehoux** [comment]
Looks like a deprecation https://github.com/django/django/commit/4d78d7338cc5cfaa0afcfc9d240d753328bbf399

**Comment by martinlehoux** [comment]
I made a PR on your PR https://github.com/ckarli/django-computedfields/pull/1

With this all tests succeed, all tests pass, except the psycopg3 matrix

**Comment by jerch** [comment]
Trying to fix the docs madness in #141 - once thats merged into master, plz apply it here as well.

**Comment by martinlehoux** [comment]
Yes I saw that, I ignored it but thanks for the fix ;)

**Comment by jerch** [comment]
Guess thats the downside of rolling software package releases :sweat_smile: I simply tagged it with the last working version for now and re-ordered the test execution to see at least, whether the unit tests pass.

**Review by jerch — APPROVED** [review]
Gonna merge the PR, as it works now. The remaining psycopg3 error comes from strict versioning of the CI env, which is already fixed in master. No need to go the long path with another PR-PR.

Thx @ckarli & @martinlehoux for looking into this :+1:

**Pull request merged**
