### PR TITLE
better narrowing for m2m updates

### LINKED ISSUE #130: Many to many dependency triggers too many computations
Hi there!

I'm not sure if this is a bug or an expected behaviour, but I needed to report it.

Here is the simple example
```py
class HostingAdvertTypeTag(Model):
    objects: HostingAdvertTypeTagManager = HostingAdvertTypeTagManager()

    name = models.CharField(max_length=100, unique=True)

class HostingAdvert(Model):
	hosting_advert_type_tags = models.ManyToManyField(
        HostingAdvertTypeTag, blank=True, related_name="hosting_adverts"
    )

	@computed(
        ArrayField(models.CharField(null=False, blank=True, max_length=100), default=list, blank=True),
        depends=[
            ["hosting_advert_type_tags", ["name"]],
        ],
        prefetch_related=["hosting_advert_type_tags"],
    )
    def all_hosting_advert_type_tag_names(self) -> list[str]:
		...
```

The issue is that when I use
```py
hosting_advert.hosting_type_tags.set(HostingAdvertTypeTag.objects.filter(name__contains="POOL"))
```

there is a computation happening for all hosting adverts in my database, not only this one (as I would expect)

It seems that the dependency graph thinks this is the correct behaviour 
image

What do you think? Is there something I didn't get about many to many fields?

The issue occurs with version 0.2.3, but also with version 0.2.1

### PR DESCRIPTION
**Pull request by jerch**
TODO:
- [x] optimize M2M updates by narrowing to M2M signal instance
- [x] explicit test cases
- [x] proxy checks

Should fix #130.

### CODE REVIEW

**Comment by jerch** [comment]
@martinlehoux This will still need some iterations before it can get merged for these reasons:
- does not work yet for proxy models (already have local patch for it)
- need to come up with some more extensive tests to spot possible regressions

The main issue with m2m fields is the fact, the m2m fields are m:1:n relations under the hood, which means the resolver has to fan out updates in two directions (in your test example that would be deps on `Advert.tags` and on `Tag.advert_set`). I am not quite sure yet, if the stricter narrowing here will lead to missed updates under certain circumstances, thus I have to revisit extisting test cases and prolly write a few more on top.

**Comment by martinlehoux** [comment]
Yes, makes total sense. At least the dependency graph does its job and shows that all_tags depends on tags.adverts, so even if not expected in the first place, it's documented.
Depending on how long you think this would take, you could add this in the documentation? I read the part around m2m gotchas, but didn't find an answer to my specific question.

**Comment by martinlehoux** [comment]
Hi @jerch , is there anything I can do to help you on this matter?

**Comment by jerch** [comment]
@martinlehoux Ah sorry, the issue went kinda out of focus. I hope to get to it by the weekend, there is one more edge case I need to test, if it passes we can add it.

**Comment by jerch** [comment]
@martinlehoux Added the missing proxy model fixes & test cases, now passing all tests. I am still not quite sure, if the proxy fixes cover all edge cases, but I was not able to provoke a faulty case with any test I could think of.

Therefore I think this good enough to be added.

**Comment by martinlehoux** [comment]
Thanks a lot! I will try to confirm this in our app :)

**Pull request merged**
